events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Primer IP Whitelist-a
        # Ovde dole možete dodati IP adresu vašeg računara ili telefona
        # Format je: allow IP_ADRESA;
        
        # Dozvoli lokalni pristup (za testiranje na istom racunaru)
        allow 127.0.0.1;
        
        # Dodajte IP adresu vašeg računara na LAN mrezi (npr. 192.168.1.X)
        # allow 192.168.1.100;
        
        # Dodajte IP adresu vašeg telefona ovde:
        # allow 192.168.1.50;

        # Dozvoli slobodan pristup iz cele lokalne mreze za pocetak
        # (Obrisite ili stavite # ispred ove linije kada zelite da zakljucate mrezu samo na specifične IP adrese iznad)
        allow 192.168.0.0/16; 
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;

        # Zabrani svima ostalima
        deny all;

        location / {
            proxy_pass http://sim_app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
